In [ ]:
import pandas as pd

In [ ]:
pip install pyspark

Collecting pyspark
  Downloading pyspark-3.1.2.tar.gz (212.4 MB)
     |████████████████████████████████| 212.4 MB 69 kB/s
Collecting py4j==0.10.9
  Downloading py4j-0.10.9-py2.py3-none-any.whl (198 kB)
     |████████████████████████████████| 198 kB 62.3 MB/s
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.1.2-py2.py3-none-any.whl size=212880768 sha256=783f67d9d96b38ce2d668eb220a3e6ec9c7aa7ab4eebabfb0f4b114384394b17
  Stored in directory: /root/.cache/pip/wheels/a5/0a/c1/9561f6fecb759579a7d863dcd846daaa95f598744e71b02c77
Successfully built pyspark
Installing collected packages: py4j, pyspark
Successfully installed py4j-0.10.9 pyspark-3.1.2

In [ ]:

from google.colab import files
  
  
uploaded = files.upload()

Saving sales_listings.1.csv.gz to sales_listings.1.csv (1).gz

In [ ]:
df = spark.read.csv("sales_listings.1.csv (1).gz")

NameError: ignored

In [ ]:
df = pd.read_csv('pluto_dtbk.csv')

In [ ]:
df

      Unnamed: 0 borough  block   lot  ...  dcpedited   latitude  longitude  notes
0             67      BK    397     6  ...        NaN  40.685062 -73.991274    NaN
1            246      BK     20    14  ...        NaN  40.704088 -73.985548    NaN
2            346      BK    241  7501  ...          t  40.695788 -73.996008    NaN
3            369      BK    253    26  ...        NaN  40.693853 -73.996138    NaN
4            375      BK    251    25  ...          t  40.694630 -73.997176    NaN
...          ...     ...    ...   ...  ...        ...        ...        ...    ...
3353      856441      BK    301    23  ...          t  40.687892 -73.995864    NaN
3354      856459      BK    305    50  ...          t  40.688026 -73.998565    NaN
3355      856460      BK    305    51  ...          t  40.688057 -73.998551    NaN
3356      856461      BK    305    52  ...          t  40.688084 -73.998532    NaN
3357      857656      BK     86    75  ...          t  40.698104 -73.987284    NaN

[3358 rows x 91 columns]

In [ ]:
!tar xvzf abc.tar.gz

SyntaxError: ignored